[package]
name = "pastebin"
version = "0.0.0"
publish = false

[dependencies]
rocket = "0.4.0"
rand = "0.6.5"
#multipart = "0.16.1"
toml = "0.4.10"
serde = "1.0.88"
serde_derive = "1.0.88"
adjective_adjective_animal = "0.1.0"
#syntect = "2.1.0"
